// require("./js/libs/pixi");
// require("./js/libs/fpsmeter");
// require("./js/libs/lz-string");
require("./js/core");
require("./js/managers");
require("./js/objects");
require("./js/scenes");
require("./js/sprites");
require("./js/windows");
require("./js/plugins");
require("./js/main");
